services:
    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'
        # Uncomment to enable authentication
        calls:
            - ['authenticate', ['%env(GITHUB_USERNAME)%', '%env(GITHUB_SECRET)%', '%env(GITHUB_AUTH_METHOD)%']]
            - ['addCache', ['@cache.app']]

    Github\HttpClient\Builder:
        arguments:
            - '@?Http\Client\HttpClient'
            - '@?Http\Message\RequestFactory'
            - '@?Http\Message\StreamFactory'

    Github\ResultPager:
        arguments:
            - '@Github\Client'

when@test:
    services:
        Github\Client: ~

        Github\ResultPager:
            arguments:
                - '@Github\Client'
