services:
    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'
        # Uncomment to enable authentication
        calls:
            - ['authenticate', ['%env(GITHUB_USERNAME)%', '%env(GITHUB_SECRET)%', '%env(GITHUB_AUTH_METHOD)%']]
            - ['addCache', ['@Cache\Adapter\Predis\PredisCachePool']]

    Github\HttpClient\Builder:
        arguments:
            - '@?Http\Client\HttpClient'
            - '@?Http\Message\RequestFactory'
            - '@?Http\Message\StreamFactory'

    Github\ResultPager:
        arguments:
            - '@Github\Client'
