sentry:
    dsn: '%env(resolve:SENTRY_DSN)%'
    messenger:
        enabled: true # flushes Sentry messages at the end of each message handling
        capture_soft_fails: true # captures exceptions marked for retry too
    options:
        environment: '%kernel.environment%'
        ignore_exceptions:
            - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
