snc_redis:
    clients:

# Define your clients here. The example below connects to database 0 of the default Redis server.
#
# See https://github.com/snc/SncRedisBundle/blob/master/Resources/doc/index.md for instructions on
# how to configure the bundle.
        default:
            type: predis
            alias: default
            dsn: "redis://%env(resolve:REDIS_HOST)%:6379"
