version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: badge-poser-nginx
    depends_on:
      - phpfpm
    working_dir: /application
    volumes:
      - .:/application
      - ./sys/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8001:80"
    networks:
      - application-network

  phpfpm:
    build: sys/dev/php-fpm
    container_name: badge-poser-phpfpm
    depends_on:
      - redis
    working_dir: /application
    volumes:
      - .:/application:cached
      - ./sys/dev/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    ports:
      - "9000:9000"
    networks:
      - application-network

  node:
    container_name: badge-poser-node
    image: node:16.13.1-alpine3.12
    user: "node"
    working_dir: /application
    volumes:
      - .:/application:cached
    networks:
      - application-network

  redis:
    container_name: badge-poser-redis
    image: redis:6.0.8-alpine3.12
    ports:
      - "6379:6379"
    networks:
      - application-network
    sysctls:
      # WARNING: The TCP backlog setting of 511 cannot be enforced because
      # /proc/sys/net/core/somaxconn is set to the lower value of 128.
      net.core.somaxconn: 1024


#Docker Networks
networks:
  application-network:
    driver: bridge
