version: '3.8'

services:
  nginx:
    container_name: badge-poser-nginx
    image: nginx:alpine
    working_dir: /application
    depends_on:
      - phpfpm
    volumes:
      - .:/application:cached
      - ./docker/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8001:80

  phpfpm:
    build:
      context: docker/dev/php-fpm
      network: host
    container_name: badge-poser-phpfpm
    working_dir: /application
    depends_on:
      - redis
    volumes:
      - .:/application:cached
      - ./docker/dev/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini:ro
    ports:
      - 9000

  node:
    container_name: badge-poser-node
    image: node:12-alpine
    user: "node"
    volumes:
      - .:/application:cached
    working_dir: /application

  redis:
    image: redis:alpine
    container_name: badge-poser-redis
    ports:
      - 6379:6379
