version: '3.7'

services:
  web:
    container_name: badge-poser-bref
    image: bref/fpm-dev-gateway
    ports:
      - '8000:80'
    volumes:
      - .:/var/task
    depends_on:
      - php
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public

  php:
    container_name: badge-poser-php
    build:
     context: docker/dev/php-fpm
     network: host
    volumes:
        - .:/var/task:ro
        - ./var:/var/task/var
    depends_on:
      - redis
    environment:
      DOCKER_COMPOSE: 1

  console:
    container_name: badge-poser-console
    image: bref/php-74
    volumes:
      - .:/var/task:ro
    entrypoint: php

  node:
    container_name: badge-poser-node
    image: node:12-alpine
    user: "node"
    volumes:
      - .:/application:cached
    working_dir: /application

  redis:
    container_name: badge-poser-redis
    image: redis:alpine
    ports:
      - "6379:6379"
