version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: sys/docker/alpine-nginx/Dockerfile
      network: host
    container_name: badge-poser-nginx
    depends_on:
      - phpfpm
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    ports:
      - 8001:80
    volumes:
      - .:/application:cached
      - ./sys/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /application

  phpfpm:
    build:
      context: .
      dockerfile: sys/docker/alpine-phpfpm/Dockerfile
      network: host
    container_name: badge-poser-phpfpm
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    env_file:
      - ./.env
    ports:
      - 9000:9000
    volumes:
      - .:/application:cached
      - ./sys/php/php.ini-dev:/usr/local/etc/php/php.ini:ro
      - ./sys/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    working_dir: /application

  redis:
    container_name: badge-poser-redis
    image: redis:6.0.8-alpine3.12
    ports:
      - 6379:6379
