version: '3.8'

services:
  webserver:
    image: bref/fpm-dev-gateway
    container_name: badge-poser-bref
    depends_on:
      - php
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
    env_file:
      - ./.env
      - ./.env.local
    environment:
      - ENABLE_CW=0
    ports:
      - 8001:80
    volumes:
      - .:/var/task
    environment:
      HANDLER: public/index.php
      DOCUMENT_ROOT: public

  php:
#    image: bref/php-80-fpm-dev
    build:
      context: .
      #dockerfile: sys/docker/alpine-phpfpm/Dockerfile
      dockerfile: sys/docker/Dockerfile
      network: host
    container_name: badge-poser-php
    volumes:
      - .:/var/task:ro
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
    env_file:
      - ./.env
      - ./.env.local
    environment:
      DOCKER_COMPOSE: 1
    ports:
      - 9000:9000
    volumes:
      - .:/var/task:ro
      - ./var:/var/task/var
    working_dir: /application

  console:
    container_name: badge-poser-console
    image: bref/php-80
    volumes:
      - .:/var/task:ro
    entrypoint: php

  node:
    container_name: badge-poser-node
    image: node:14.14.0-alpine3.12
    user: "node"
    volumes:
      - .:/application:cached
    working_dir: /application

  redis:
    container_name: badge-poser-redis
    image: redis:6.0.8-alpine3.12
    ports:
      - 6379:6379
    sysctls:
      # WARNING: The TCP backlog setting of 511 cannot be enforced because
      # /proc/sys/net/core/somaxconn is set to the lower value of 128.
      net.core.somaxconn: 1024
