version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: sys/docker/alpine-nginx/Dockerfile
      network: host
    container_name: badge-poser-nginx
    depends_on:
      - phpfpm
    env_file:
      - ./.env
      - ./.env.local
      - ./.env.test
    working_dir: /application
    volumes:
      - .:/application
      - ./sys/nginx/default.conf.template.dev:/etc/nginx/templates/default.conf.template
    ports:
      - "8001:80"
    networks:
      - application-network

  phpfpm:
    build:
      context: .
      dockerfile: sys/docker/alpine-phpfpm/Dockerfile
      network: host
    container_name: badge-poser-phpfpm
    depends_on:
      - redis
    env_file:
      - ./.env
      - ./.env.local
    working_dir: /application
    command: |
      /bin/sh -c "
        apk --no-cache add shadow
        usermod -u 1000 www-data
        groupmod -g 1000 www-data
        chown -R www-data: /application
        php-fpm
      "
    volumes:
      - .:/application
      - ./sys/php/php.ini-dev:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - "9000:9000"
    networks:
      - application-network

  node:
    container_name: badge-poser-node
    image: node:16.17.1-alpine3.16
    user: "node"
    working_dir: /application
    volumes:
      - .:/application:cached
    networks:
      - application-network

  redis:
    container_name: badge-poser-redis
    image: redis:6.0.8-alpine3.12
    ports:
      - "6379:6379"
    networks:
      - application-network
    sysctls:
      # WARNING: The TCP backlog setting of 511 cannot be enforced because
      # /proc/sys/net/core/somaxconn is set to the lower value of 128.
      net.core.somaxconn: 1024


#Docker Networks
networks:
  application-network:
    driver: bridge
