version: '3.8'

services:
  nginx:
    build:
      dockerfile: sys/docker/nginx/Dockerfile
      context: .
      network: host
    container_name: badge-poser-nginx
    working_dir: /application
    depends_on:
      - phpfpm
    volumes:
      - .:/application:cached
    ports:
      - 8001:80

  phpfpm:
    build:
      dockerfile: sys/docker/php/Dockerfile
      context: .
      network: host
    container_name: badge-poser-phpfpm
    working_dir: /application
    depends_on:
      - redis
    volumes:
      - .:/application:cached
      - ./sys/php/php-ini-overrides.ini-dev:/etc/php/7.4/fpm/conf.d/99-overrides.ini:ro
    ports:
      - 9000:9000

  node:
    container_name: badge-poser-node
    image: node:14-alpine
    user: "node"
    volumes:
      - .:/application:cached
    working_dir: /application

  redis:
    image: redis:alpine
    container_name: badge-poser-redis
    ports:
      - 6379:6379
