imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true

web_profiler:
    toolbar: false
    intercept_redirects: false

# for functional test
services:
    stats_persister:
        class: PUGX\StatsBundle\Service\NullPersister
