imports:
    - { resource: parameters.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_proxies: ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ PUGXBadgeBundle ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar

pugx_badge:
    allin_badges: ['latest_stable_version', 'total', 'latest_unstable_version', 'license']
    badges:
        - { name: 'latest_stable_version', label: 'Latest Stable Version', route: "pugx_badge_version_latest", latest: 'stable'}
        - { name: 'total', label: 'Total Downloads', route: "pugx_badge_download" }
        - { name: 'latest_unstable_version', label: 'Latest Unstable Version', route: "pugx_badge_version_latest", latest: 'unstable'}
        - { name: 'license', label: 'License', route: "pugx_badge_license"}
        - { name: 'monthly', label: 'Monthly Downloads', route: "pugx_badge_download_type", type: 'monthly'}
        - { name: 'daily', label: 'Daily Downloads', route: "pugx_badge_download_type", type: 'daily'}
        - { name: 'version', label: 'Version', route: "pugx_badge_version" }


snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%redis_hostname%/%redis_database_default%

