imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ PUGXBadgeBundle ]
    java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar

pugx_badge:
    badges:
        - { name: 'total', label: 'Total Downloads', route: "pugx_badge" }
        - { name: 'monthly', label: 'Montly Downloads', route: "pugx_badge_stat", type: 'monthly'}
        - { name: 'daily', label: 'Daily Downloads', route: "pugx_badge_stat", type: 'daily'}
        - { name: 'version', label: 'Version', route: "pugx_badge_version" }
        - { name: 'latest_stable_version', label: 'Latest Stable Version', route: "pugx_badge_version_latest", latest: 'stable'}
        - { name: 'latest_unstable_version', label: 'Latest Unstable Version', route: "pugx_badge_version_latest", latest: 'unstable'}

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://%redis_hostname%/%redis_database_default%

