parameters:
    pugx.poser.class: 'App\Tests\Service\PoserStub'

services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

    App\Service\SnippetGeneratorInterface: '@App\Tests\Service\SnippetGeneratorStub'
    App\Stats\Persister\PersisterInterface: '@App\Stats\Persister\NullPersister'

    App\Service\ReaderInterface: '@App\Service\RedisReader'

    App\Tests\Service\SnippetGeneratorStub:
        class: App\Tests\Service\SnippetGeneratorStub

    test.Predis\Client: '@snc_redis.default'