name: Test

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        php-versions: [ '8.3' ]
        coverage-driver: [ 'pcov' ]

    services:
      redis:
        image: redis:7.0
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        args: --prefer-dist
        version: 2
        php_extensions: gd
        php_version: 8.3

    - name: Yarn install
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.1'
    - run: yarn install

    - name: Rebuild sass
      run: npm rebuild node-sass

    - name: Build frontend
      run: yarn build

    - name: checks that the YAML config files contain no syntax errors
      run: ./bin/console lint:yaml config

    - name: checks that the Twig template files contain no syntax errors
      run: ./bin/console lint:twig templates

    - name: run stylelint checks
      run: yarn stylelint

    - name: Coding Standard Checks
      run: PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer fix --dry-run -v

    - name: "Run tests with phpunit/phpunit"
      run: "bin/phpunit -d memory_limit=-1 --coverage-clover clover.xml"
      env:
        REDIS_HOST: localhost

    - name: PHPStan
      run: ./vendor/bin/phpstan analyse -c phpstan.neon --level=8 "src"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  docker:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Check Docker Version
      run: docker --version
    - name: Install Latest Docker
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
        sudo apt-get update --allow-downgrades
        sudo apt-get install docker-ce=5:24.0.5-1~ubuntu.22.04~jammy --allow-downgrades
    - name: Check Docker Version
      run: docker --version

    - name: Build
      run: make build_prod
